version: "3.8"

services:
  postgres:
    container_name: jen-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "5432:5432"
    hostname: postgres
    volumes:
      - ./migrations/1_initial.up.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    container_name: jen-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: anishsinha0128@gmail.com
      PGADMIN_DEFAULT_PASSWORD: anishsinha
    ports:
      - "8889:80"
    hostname: pgadmin
    depends_on:
      - postgres
  redis:
    container_name: jen-redis
    image: redis
    ports:
      - "6379:6379"
    hostname: redis
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - core
      - client
  core:
    hostname: core
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./server:/app
    depends_on:
      - redis
      - postgres
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    hostname: client

