version: "3.8"

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "5432:5432"
    hostname: postgres
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: anishsinha0128@gmail.com
      PGADMIN_DEFAULT_PASSWORD: anishsinha
    ports:
      - "8889:80"
    hostname: pgadmin
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    hostname: redis
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
